manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Furash 
      url-base: https://github.com/Furash
    - name: lvgl
      url-base: https://github.com/lvgl
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2
      import: app/west.yml
    - name: nice-view-gem
      remote: Furash 
      revision: main 
    - name: lvgl
      remote: lvgl
      revision: v8.4
  self:
    path: config